Codingstyle fixes (without Github actions)
turnitin/moodle-plagiarism_turnitin pull request #731
Opened 2024-07-29 14:28 UTC by lucaboesch

Referring to https://github.com/turnitin/moodle-plagiarism_turnitin/pull/728 and the discussion there.

2024-12-20 15:04 UTC, lucaboesch commented
I've updated the coding style issues again, and it would be great if they could be merged.

2024-12-20 16:35 UTC, jack-tii requested changes
Thanks so much for your continued support, this was a pretty big undertaking! There are 2 minor things I've commented on, if we can get some clarification and one minor change I'm happy to merge this now that we're at the start of our next release cycle

2024-12-20 16:35 UTC, jack-tii commented on classes/privacy/provider.php
> -
I trust that you know what you're doing by removing this, but for my own information and out of curiosity what's the reasoning for adding/removing these in a couple of places? Why for example does the privacy provider need to be accessible from scripts external to Moodle?

2024-12-21 10:05 UTC, lucaboesch commented on classes/privacy/provider.php
> -
Thanks @jack-tii !
I did remove those lines.
In regards to the 'MOODLE_INTERNAL' this might be of value: https://www.youtube.com/watch?v=TaVwRjxN_3E
Tools local/moodlecheck and local/codechecker which I heavily use do also point out omitted and superfluous usages of the command.
Best,
Luca

2025-07-07 11:06 UTC, jack-tii commented
Closing as #728 was merged

2025-07-07 11:06 UTC, closed without merging